### ISSUE TITLE
Bunch of bugs

### ISSUE THREAD

**Issue by RicardoUsbeck** [dbpedia/chatbot#13]
M: 	“What is the best Western movie?"
Bot:     	"Does that question interest you ?"
M: 	"No, I simply have too much time..."
Bot:     	"You are being a bit negative."
M: 	"No, you are simply not helpful :P"
Bot:     	"11
12
23
13
14
15
16
19
1
2
3
4
5
7
8
9
20
10
21"

In addition, we thing "Sorry, I will try better."  should be “Sorry, I will try to become better."

**Comment by ram-g-athreya** [comment]
@RicardoUsbeck I have added first two questions to the list we are maintaining. The third question **No, you are simply not helpful :P** is replied by Eliza right now. I am not able to recreate the bug.

I have changed **Sorry, I will try better.** to **Sorry, I will try to become better.**

![screen shot 2017-08-03 at 12 15 15 pm](https://user-images.githubusercontent.com/3251705/28909304-8a2ba7c4-7845-11e7-9cf9-2d426b17a2ae.png)
