### ISSUE TITLE
GSoC Documentation

### ISSUE THREAD

**Issue by RicardoUsbeck** [dbpedia/chatbot#15]
- [x] Make sure the master branch compiles
- [x] Add to http://wiki.dbpedia.org/projects
- [x] Make sure a "How to run" exists
- [x] Provide links to the running demo and dev environment 
- [x] Make sure the CI/CD is well documented (including GitFlow)
- [x] Provide an overview of the architecture
- [x] Make sure the capabilities of the bot are documented
- [x] Add Flowcharts to wiki
- [x] Add badges similar to https://github.com/dice-group/NLIWOD
- [x] Include a link in README.md to your GSoC progress wiki page

**Comment by ram-g-athreya** [comment]
Hi @RicardoUsbeck 

Where should I create the documentation? As a WikiPage here or a Google Doc?
By badges do you mean OpenHub & BetterCode?

**Comment by RicardoUsbeck** [comment]
You can use the wiki but please add to the README.md something like : "For more information about this project and GSoC, please refer to XYZ" which points to the wiki. We can only provide one link for the eval, i.e., this repository URL but need to have a way for the GSoC admins to see the documentation as well.

**Comment by ram-g-athreya** [comment]
Ok got it. Updated the link to wiki.

**Comment by RicardoUsbeck** [comment]
for the first todo: "Make sure the master branch compiles" we need to document, that it needs npm installed which was not installed on our Ubuntu 16.04 test machine
