### ISSUE TITLE
Continuous Integration with master branch 

### ISSUE THREAD

**Issue by rrichajalota** [dbpedia/chatbot#21]
I assume, currently there is no way of checking whether the last commit to master branch builds successfully or not. Maybe, we can add a 'build' badge to the repo for the same?

**Comment by ram-g-athreya** [comment]
You can check in gitlab. I will add you to the project in Gitlab. Can you create a Gitlab id and share in Slack?

**Comment by ram-g-athreya** [comment]
Also we are presently using gitflow for merging develop to master.

**Comment by RicardoUsbeck** [comment]
Please do not forget to extend the documentation in the wiki in that respect even if there are websites which need authorization

**Comment by ram-g-athreya** [comment]
Hi @RicardoUsbeck 

I have included that we use GitLab in the documentation and the pipeline which we use there (Test, Package, Deploy). Is that what you meant?

**Comment by RicardoUsbeck** [comment]
I have seen this: https://github.com/dbpedia/chatbot/wiki/GSoC-2017:-Chatbot-for-DBpedia#continuous-integration--continuous-deployment-ci--cd

But I am missing a bit information, e.g. a link to the gitlab project and so on

**Comment by ram-g-athreya** [comment]
Hi I have added the link to the GitLab project as well

**Comment by RicardoUsbeck** [comment]
@yamalight Could you add the badge?

**Comment by yamalight** [comment]
@RicardoUsbeck ok, will do

**Comment by yamalight** [comment]
Done. Pull request is here: #32
FYI, you can find them on Gitlab -> Repo settings -> CI/CD -> General pipeline settings.

**Comment by ram-g-athreya** [comment]
Hi @yamalight 

The README says pipeline **unknown** is there additional configuration that we need to do or changes we need to make in README to change the status somehow?

**Comment by yamalight** [comment]
@ram-g-athreya the gitlab project needs to be public for badge to be visible to all

**Comment by ram-g-athreya** [comment]
Hi @yamalight 

The project is public. I ran the pipeline now and the badge seems to have changed from **unknown** to **running**. So I guess it is working. 

Thanks for the help.
