### ISSUE TITLE
universities in Kaiserslautern

### ISSUE THREAD

**Issue by ram-g-athreya** [dbpedia/chatbot#26]
for "universities in Kaiserslautern” you add a third entry "fachhochschule" which is wrong.

**Comment by ram-g-athreya** [comment]
@RicardoUsbeck how exactly do I go about solving this? Any suggestions?

**Comment by RicardoUsbeck** [comment]
Is it produced by the underlying qa system?

**Comment by ram-g-athreya** [comment]
Yes it produces the following response. SPARQL query from QANARY is as follows:
**SELECT DISTINCT ?s1 where { ?s1  ?p1  <http://dbpedia.org/ontology/University> .  ?s1  ?p2  <http://dbpedia.org/resource/Kaiserslautern> .  } limit 1000**

Please note **fachhochschule** seems to come from Wolfram Alpha. Is that actually wrong? Unfortunately, I dont know much about the region.

![screen shot 2018-03-15 at 2 09 15 pm](https://user-images.githubusercontent.com/3251705/37491379-dcc3a048-285a-11e8-8fed-36b816ef905f.png)

**Comment by RicardoUsbeck** [comment]
Well it seems to be an error in the DBpedia ontology then
