### ISSUE TITLE
Scrolling not working properly sometimes

### ISSUE THREAD

**Issue by ram-g-athreya** [dbpedia/chatbot#7]
When clicking on start over in the menu in web interface the scroll doesn't work properly. 

After some conversations clicking on the + menu in the web interface makes the message container scroll to wrong position

**Comment by RicardoUsbeck** [comment]
Did that happen again since you reported the issue?

**Comment by ram-g-athreya** [comment]
I still haven't fixed it since it was low priority and I was working on other things such as deployment and documentation. I will try to finish it this week.
