### ISSUE TITLE
Showing endless loader when DBpedia is not available

### ISSUE THREAD

**Issue by yamalight** [dbpedia/chatbot#8]
Currently, dbpedia sparql endpoint is not available ("under maintenance") and that breaks the bot.
Instead of showing some error, it just shows endless loading indicator.

**Comment by RicardoUsbeck** [comment]
@LorenzBuehmann @Aklakan Wasn't there a fail-over SPARQL endpoint class somewhere?

**Comment by ram-g-athreya** [comment]
When DBpedia is down and the user asks natural language/factoid question then the bot replies with appropriate message that the service is down

![screen shot 2017-08-01 at 12 41 09 pm](https://user-images.githubusercontent.com/3251705/28813615-8d7592e4-76b7-11e7-8dda-69699a5b3180.png)

**Comment by LorenzBuehmann** [comment]
@RicardoUsbeck Yes, in the jena-sparql-api there is a class that allows to define multiple physical endpoints for the logically same dataset. But I guess this is not what you need here.

**Comment by RicardoUsbeck** [comment]
Can you paste a link please?

**Comment by LorenzBuehmann** [comment]
[This factory](https://github.com/AKSW/jena-sparql-api/blob/master/jena-sparql-api-core/src/main/java/org/aksw/jena_sparql_api/fallback/QueryExecutionFactoryFallback.java) should do the fallback procedure. Feel free to extend it with additional features if necessary.

**Comment by RicardoUsbeck** [comment]
Thanks!
